# Generated by Django 6.0 on 2025-12-18 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lemma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lemma", models.CharField(max_length=100)),
                ("gloss", models.CharField(blank=True, max_length=255)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lemmas",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "lemma")},
            },
        ),
        migrations.CreateModel(
            name="Morphology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="morphologies",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "tag")},
            },
        ),
        migrations.CreateModel(
            name="Passage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=200)),
                ("content", models.TextField(help_text="Surface text of the passage")),
                ("is_published", models.BooleanField(default=True)),
                (
                    "language_pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="languages.languagepack",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="content.manuscript",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        help_text="Position of token in passage"
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("gloss", models.CharField(blank=True, max_length=255)),
                ("audio_url", models.URLField(blank=True)),
                (
                    "lemma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.lemma",
                    ),
                ),
                (
                    "morphology",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.morphology",
                    ),
                ),
                (
                    "passage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="content.passage",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "unique_together": {("passage", "index")},
            },
        ),
    ]
