# Generated by Django 6.0 on 2025-12-18 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("ltr", "Left to Right"), ("rtl", "Right to Left")],
                        default="ltr",
                        max_length=3,
                    ),
                ),
                ("script", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LanguagePack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("features", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packs",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "version")},
            },
        ),
    ]
